import type { Metadata } from "next";
import { VideoEmbed } from "@/components/podcast/VideoEmbed";
import { EpisodeFaq, type EpisodeFaqItem } from "@/components/podcast/EpisodeFaq";
import { GrowthDiagnosticCta } from "@/components/podcast/GrowthDiagnosticCta";

/* ----------------------------------------------------------------------
   /podcast/episode-1-catering-seo-lessons
   First podcast episode page. Same editorial voice as /blog/[slug]
   (BlogArticle.tsx) — cream ground, thin-serif headings, gold links and
   markers, the site's one real <table> recipe — but hand-built as JSX
   instead of markdown, since this content shape (video, chapters,
   transcript, FAQ) doesn't fit the blog's Postgres/markdown pipeline.
   Server Component: everything below is static, so only the three
   genuinely interactive pieces (video facade, FAQ accordion, the
   Growth Diagnostic CTA) are split out as client components.
   No chart-image assets exist for this page (they were generated by an
   external pipeline that isn't part of this codebase) — the "Google vs
   Instagram" split, the 2023-vs-2026 comparison, the H1 formula, and
   the above-the-fold checklist are all built as real, brand-styled
   components instead, so nothing here depends on a missing file.
   ---------------------------------------------------------------------- */

const YOUTUBE_ID = "WtfVjOL8TiU";
const RUNTIME = "1:21:00";
const OG_IMAGE = `https://i.ytimg.com/vi/${YOUTUBE_ID}/maxresdefault.jpg`;

export const metadata: Metadata = {
  title: "Catering SEO: What 3 Years of Ranking Caterers Taught Us (Podcast Ep. 1) | LocalEyes",
  description:
    "Over 95% of our clients' leads come from Google, not Instagram. Episode 1 of the LocalEyes podcast breaks down what three years of catering SEO taught us.",
  alternates: {
    canonical: "/podcast/episode-1-catering-seo-lessons",
  },
  openGraph: {
    title: "What Three Years of Catering SEO Actually Taught Us",
    description:
      "Over 95% of our clients' leads come from Google, not Instagram. Episode 1 of the LocalEyes podcast breaks down what three years of catering SEO taught us.",
    images: [{ url: OG_IMAGE, width: 1280, height: 720, alt: "LocalEyes Podcast — Episode 1" }],
    type: "video.other",
  },
  twitter: {
    card: "summary_large_image",
    images: [OG_IMAGE],
  },
};

/* ============================ CONTENT ================================ */

const SHORT_VERSION = [
  "Google is the lead source. Instagram is the brochure. Our client data puts over 95% of inbound leads on Google, and that includes clients with large, genuinely good Instagram accounts.",
  "Your website is not a portfolio piece. It is the storefront. Kent spent close to a decade treating a website like a business card and lost years of bookings to that assumption.",
  "Events are the business, not the bonus. If you are running farmers markets and treating catering inquiries as upside, you have the model backwards.",
  "The H1 is the fastest fix on most sites. Fixing the H1 alone has moved sites from page three to page one. It should answer three questions: what you do, who you do it for, and where.",
  "Reviews compound on cadence, not volume. Thirty reviews arriving weekly beats fifty that stopped a year ago.",
  "Corporate beats weddings on repeat value. A wedding is one event. A corporate client can be quarterly, sometimes monthly, and the average ticket is often higher.",
  "AI-generated city pages are a liability. Duplicated location pages get ignored or suppressed, and the recovery can take six months or more.",
  "The market is not open anymore. Three years ago the pitch was “nobody here is doing SEO.” Now the question is whose SEO is better.",
  "Everyone writes the same headline. “Elevate your event” is on a startling number of catering sites. If your copy could belong to any competitor, it is not doing SEO work or brand work.",
];

const ERA_COMPARISON = [
  { label: "The pitch", y2023: "“The market is wide open, get in now”", y2026: "“Whose SEO is better”" },
  { label: "Main objection", y2023: "“What even is SEO, how long will it take”", y2026: "“How are you different from the last agency”" },
  { label: "Competing spend", y2023: "Instagram", y2026: "Other SEO agencies" },
  { label: "Typical site", y2023: "One page, thin, zero optimization", y2026: "Multi-page, AI-filled, all identical" },
  { label: "Copy", y2023: "Written by the owner", y2026: "Written by ChatGPT, and it shows" },
  { label: "Time to top 3 in a major city", y2023: "Weeks, sometimes 2 months", y2026: "Still possible in 2 to 3 months, but only with authority and reviews behind it" },
  { label: "What wins", y2023: "Being the only optimized site in the city", y2026: "Content quality, review cadence, site structure" },
];

const ABOVE_FOLD_ITEMS = [
  { n: "01", text: "Clean nav, few links, CTA button on the right" },
  { n: "02", text: "Hero image or short video with a person in it, ideally behind the cart, smiling" },
  { n: "03", text: "H1 answering the three W’s" },
  { n: "04", text: "One primary CTA, phrased as a quote request rather than a booking" },
  { n: "05", text: "Social proof directly below the CTA, not floated at the top" },
  { n: "06", text: "The whole thing readable on a phone, since roughly half of catering traffic is mobile" },
];

const REVIEW_TACTICS = [
  { tactic: "A-frame sign at the front of the queue", where: "At the cart, during service", why: "People in line are standing still with a phone in hand. It is free real estate." },
  { tactic: "Secret menu item for a review", where: "At the point of order", why: "Converts a request into a small trade rather than a favor" },
  { tactic: "“Every review tips our baristas”", where: "Corporate events with no tip jar", why: "Corporate hosts often ban tip jars. This routes the same generosity somewhere useful." },
  { tactic: "One staff member making the ask out loud", where: "Mid-service, when a queue forms", why: "“Our goal tonight is ten reviews with a photo, I will pose” converts far better than a card" },
  { tactic: "Weddings specifically", where: "Any wedding booking", why: "Operators across the country are seeing unusually high review rates at weddings right now. Guests are relaxed and want to support the vendors." },
];

const CHAPTERS = [
  { t: "0:00", topic: "Intro and what this episode covers" },
  { t: "2:16", topic: "Where the name LocalEyes came from" },
  { t: "3:10", topic: "Kent’s failed coffee cart and what it taught him" },
  { t: "7:37", topic: "The one thing he wishes someone had told him" },
  { t: "9:17", topic: "Selling SEO to coffee caterers in 2023" },
  { t: "12:32", topic: "Instagram versus Google, and how that argument ended" },
  { t: "15:25", topic: "“Elevate your event” and why every site reads the same" },
  { t: "17:05", topic: "Pushing the industry toward corporate events" },
  { t: "20:18", topic: "What caterers get wrong about communicating their business" },
  { t: "23:27", topic: "Why we expanded past coffee catering" },
  { t: "25:06", topic: "Breaking into New York, Chicago, Miami and Dallas" },
  { t: "29:06", topic: "Site structure: service pages and location pages" },
  { t: "30:15", topic: "The hero section, line by line" },
  { t: "33:38", topic: "Fresh content and the review cadence" },
  { t: "35:27", topic: "Building a review engine at the cart" },
  { t: "39:38", topic: "The visuals trap" },
  { t: "41:44", topic: "The first warning sign on a site with no leads" },
  { t: "43:35", topic: "The three W’s H1 formula" },
  { t: "45:25", topic: "Does SEO clash with branding" },
  { t: "47:36", topic: "Why DIY AI SEO does not rank" },
  { t: "50:50", topic: "Duplicate city pages and getting suppressed" },
  { t: "52:54", topic: "Client results, named cities and timelines" },
  { t: "58:42", topic: "The New York client who doubled revenue" },
  { t: "1:04:19", topic: "The new site and the free Growth Assessment" },
  { t: "1:07:23", topic: "The coffee catering price calculator" },
  { t: "1:09:31", topic: "The catering knowledge base agent" },
  { t: "1:11:38", topic: "Client dashboards and why we run on group texts" },
  { t: "1:13:48", topic: "Rapid fire" },
  { t: "1:20:47", topic: "One piece of advice for someone starting tomorrow" },
];

type Turn = { speaker: string; lines: string[] };
type TranscriptSection = { heading: string; time: string; turns: Turn[] };

const TRANSCRIPT: TranscriptSection[] = [
  {
    heading: "On where the name came from",
    time: "2:16",
    turns: [
      { speaker: "Kent", lines: [
        "It came from not overthinking it. I have gotten stuck naming companies before. Local SEO, local attention, local traffic, LocalEyes. I told Zane we would call it that and come up with something better later. We never did.",
      ] },
      { speaker: "Zane", lines: [
        "The local part came from wanting to start with local businesses, because jumping straight to anything grander would have been very hard. The “eyes” part is just visibility.",
      ] },
    ],
  },
  {
    heading: "On the coffee cart that failed",
    time: "3:39",
    turns: [
      { speaker: "Kent", lines: [
        "I would not really call it a business. It was me failing completely at having a coffee cart. What it taught me was how to present yourself online, because I did not. I did farmers markets like everyone did before event catering became a thing. Then I did one wedding, one event, and thought, this is so much easier, getting paid up front. It still did not click that it was the business.",
        "I also ran an online coffee company for six years and did everything wrong there on SEO too. So I get to talk to people in the coffee and cafe space and say honestly, I was in your shoes.",
      ] },
      { speaker: "Gvantsa", lines: [
        "How often on a call do you think, I have been in exactly this position?",
      ] },
      { speaker: "Kent", lines: [
        "As soon as I hear the words farmers market. You have a mobile setup that was never built to be mobile, the plumbing shakes loose, the circuit trips, and then you stand in a booth for eight hours hoping someone walks by. At some point you are faking a smile watching people pass. There is a better way, and it is more profitable and it does not drain you.",
      ] },
    ],
  },
  {
    heading: "On what he wishes someone had told him",
    time: "7:37",
    turns: [
      { speaker: "Kent", lines: [
        "Events and catering are the business, not the bonus. I was treating an event inquiry as a nice surprise while my main gig was standing on a corner in Bend, Oregon for seven hours to sell three drinks.",
        "And take the website seriously. For almost a decade I thought a website was a portfolio piece, something to look cool and represent the brand. It is the new version of Main Street. People used to fight over the best storefront on the block because that is where everyone walked past. Your website is that.",
      ] },
    ],
  },
  {
    heading: "On selling SEO three years ago",
    time: "9:17",
    turns: [
      { speaker: "Zane", lines: [
        "People were hesitant because they were not making much money yet. The gate you had to open was showing them what organic leads could return. Most of them had genuinely average websites with zero optimization. Once they heard the market was wide open in their city and they could be found for conferences and corporate events, they would take the shot.",
      ] },
      { speaker: "Kent", lines: [
        "I was on those calls. The pushback then was different. People questioned what SEO even was. It was not part of the standard blueprint for caterers. And Instagram came up constantly, people deciding between social and their site. It took time before people understood Instagram was a vanity metric, not a lead engine.",
      ] },
    ],
  },
  {
    heading: "On the Instagram question today",
    time: "17:26",
    turns: [
      { speaker: "Kent", lines: [
        "The other day I still had someone on a sales call who thought Instagram could be a major lead source. I have the data. Over 95% of our clients’ leads come from Google. The customers say they came from Google. These are clients with genuinely great Instagram accounts and big followings, and it is still under 10% of leads. A big following does not mean those people are your customers.",
      ] },
    ],
  },
  {
    heading: "On pushing the industry toward corporate",
    time: "18:40",
    turns: [
      { speaker: "Kent", lines: [
        "Weddings are easier to get, but if you tailor your services and your site to appeal to high-end corporate clients, your average ticket can double and the gigs get bigger. Two and three day events. Repeat clients. With a wedding you get one wedding. We have clients running quarterly events with the same corporate account, and some doing monthly coffee service in offices.",
      ] },
      { speaker: "Zane", lines: [
        "We try to put these businesses in front of event planners specifically. That is a segment we learned how to be visible to. A planner is not one event, it is a stream of them.",
      ] },
    ],
  },
  {
    heading: "On what caterers get wrong",
    time: "21:38",
    turns: [
      { speaker: "Gvantsa", lines: [
        "We call ourselves SEO specialists but we do more growth marketing. We work on conversion rates, design, and consulting on the business, and we do not consider a client successful just because traffic went up. We track leads.",
        "The thing most people get wrong is communication. It is one thing to bring a user to your site and another to give them the information they need. You see these one-page sites cramming everything into a single place. What you do, what it costs, what you specialize in. Users have to get that as fast as possible.",
      ] },
    ],
  },
  {
    heading: "On the hero section",
    time: "30:15",
    turns: [
      { speaker: "Zane", lines: [
        "Start at the top. Clean logo, a few links, CTA button on the right. Most sites have that already. Then the hero. Something inviting where somebody can picture you at their event. A person, a smile, a person behind the cart, even a short video. Text next to it, and an H1 that is properly optimized, because that is the first thing Google latches onto.",
      ] },
      { speaker: "Gvantsa", lines: [
        "The hero matters because it cannot be crowded and it cannot be exhausting. You have to hand-pick what goes there. Users are lazier than you think and they will not dig through your site for the thing you needed them to see. Our whole job in that space is moving someone from “I am interested” to “I have to reach out.”",
      ] },
    ],
  },
  {
    heading: "On reviews and fresh content",
    time: "33:38",
    turns: [
      { speaker: "Zane", lines: [
        "Fresh content, consistently. Updates, event photos, and reviews on Google. The way Google reads reviews together with your site has completely changed. If you have a profile stuck on the same reviews for three months, and someone else with a worse site is getting reviews steadily, Google puts those two things together and moves them up past you.",
      ] },
      { speaker: "Kent", lines: [
        "Let me drop some gold. When Valor started taking catering seriously I was using their headquarters as my office, sitting next to Joey, and I said we need a review engine. Buy a stand that goes in front of the cart. There is a line at every event. That is free real estate. Ask for the review right there, and incentivize it. A secret menu item. Or instead of a tip jar, every review tips our baristas, which matters because a lot of corporate hosts do not want a tip jar out.",
        "If you have three staff and a queue, one person can look up and say, our goal tonight is ten reviews with a picture, I will pose. Bring energy to it. Nobody responds to “can you leave us a review.”",
        "And the cadence matters more than the count. If you are at 30 and getting one a week, you will jump the person sitting at 50 before you even reach 50 yourself.",
      ] },
    ],
  },
  {
    heading: "On the visuals trap",
    time: "39:38",
    turns: [
      { speaker: "Gvantsa", lines: [
        "Visuals are good and necessary, but they do not bring you leads. A lot of clients direct us to work on visuals, and we are happy to, we build sites that convert. Coffee catering is a visual business. But what brings the leads is well-structured, useful content, correct headers, and the technical work underneath.",
        "My opinion is bring people to the site first, then work on how it converts. Caterers focus on visuals partly because it is the most tangible thing they can see. The technical work is invisible.",
        "It is like having an amazing restaurant in the middle of nowhere that nobody can find.",
      ] },
    ],
  },
  {
    heading: "On the H1",
    time: "41:44",
    turns: [
      { speaker: "Gvantsa", lines: [
        "We had one client with a beautiful site built in JavaScript, which is not SEO friendly and they had no way of knowing that. But other than that, it is always the H1. Either the text is there but not marked up so Google does not recognize it as the main header, or it is catchy marketing copy with no keyword and no description in it. When I see that, I know a correct header will produce an increase fairly soon. It is a quick win, and then you find the next thing.",
        "The formula is what you do, who you do it for, and where. Three W’s, answered immediately. For a cocktail catering business in New York, something like cocktail bar catering and professional bartenders in New York City for corporate and private events. Not too long, fits on screen, delivers everything.",
      ] },
      { speaker: "Kent", lines: [
        "People get romantic about their copy. That is how you end up with “Lattes, Love and Laughs” as an H1, or just the company name. First get people to the site. Then make it cool.",
      ] },
    ],
  },
  {
    heading: "On SEO versus branding",
    time: "45:25",
    turns: [
      { speaker: "Kent", lines: [
        "Everyone thinks they clash. There is a middle. Take the extreme: a technically perfect site that is impossible to use. It will never book anyone, and then it actually hurts your SEO, because time on site goes to zero. Google watches people click your link and bounce straight back to the results, and stops recommending you. So they go hand in hand. You can over-optimize and play the game, but it has to be built for humans or it drops.",
      ] },
    ],
  },
  {
    heading: "On DIY AI SEO",
    time: "47:36",
    turns: [
      { speaker: "Gvantsa", lines: [
        "Wrong keywords, first. AI gets its data from what is already on Google. If the businesses in your market are not optimized, the model has learned the wrong patterns and hands them back to you.",
        "Second, duplication. All of that content looks the same. If it is exhausting for me it is exhausting for users. Google does not keep those pages to show anyone. They exist in your sitemap and serve no purpose.",
      ] },
      { speaker: "Zane", lines: [
        "Two tests for one of those pages. It should be linked from somewhere else on your site. And it should come up above your home page for the thing it is about. If your home page is still ranking for that query instead, what was the page for?",
      ] },
      { speaker: "Gvantsa", lines: [
        "A whole site can effectively get hidden for duplicate content. Google will not tell you. The recovery can take six months or more. You can have a perfectly optimized page, fresh reviews, no reason not to be number one, and the rest of the site is what is holding it down.",
      ] },
    ],
  },
  {
    heading: "On results",
    time: "54:14",
    turns: [
      { speaker: "Zane", lines: [
        "Number one spots in LA, Chicago, New York, Miami and a couple of big Texas cities. Early on, clients making jumps within one or two months in major markets and holding them. We still see top three and top five inside two months when the site has authority, consistent reviews, and is not a brand new domain.",
      ] },
      { speaker: "Kent", lines: [
        "One of our first LA clients hit number one for coffee catering in Los Angeles within about two months and stayed with us for years while that market got significantly harder.",
        "The one I like most is a New York operator I reached out to personally. Before the call I thought, why would she sign with me, she is already position three on her best keyword and middle of page one otherwise, which is very good for New York. She was already making real money. I got on the call and said, you are good on these three keywords, here are ten more you are not ranking for at all. There is money on the table. Her revenue has roughly doubled since.",
        "That is the pattern. You can believe you are number one because you are number one for the two keywords you happen to check.",
      ] },
    ],
  },
];

const RAPID_FIRE: { q: string; a: string }[] = [
  { q: "Google Ads or SEO?", a: "Zane: SEO." },
  { q: "One thing every catering website needs?", a: "Zane: a booking form." },
  { q: "One SEO myth you wish would disappear?", a: "Gvantsa: PageSpeed Insights as a scoreboard. Zane disagreed, on the record, and won on a technicality." },
  { q: "Reviews or backlinks?", a: "Kent: in catering, probably backlinks." },
  { q: "Beautiful website or clear website?", a: "Zane: beautiful. And clear." },
  { q: "More traffic or better leads?", a: "Better leads." },
  { q: "One question every business owner should ask their marketing agency?", a: "Gvantsa: how do you track your results, and what does success actually look like. Kent: if you were in my shoes, what would you do?" },
  { q: "One expense caterers underestimate?", a: "Zane: photography, and second carts. A couple of genuinely good shoots will out-perform a gallery of iPhone screenshots in a competitive city." },
  { q: "One piece of advice for someone starting tomorrow?", a: "Zane: get the website. Do not just count on Instagram. Build every channel that can bring you a lead, then grow them." },
];

const FAQ_ITEMS: EpisodeFaqItem[] = [
  {
    q: "Is SEO or Instagram better for getting catering leads?",
    a: "Google, and it is not close. Across our client base over 95% of inbound leads come from Google and under 10% from Instagram, including clients with large followings. Instagram is where a lead confirms you look legitimate after they have already found you. Search is where they find you in the first place, with intent and a date in mind.",
  },
  {
    q: "How long does catering SEO take to work?",
    a: "In this niche, faster than SEO usually does. We regularly see meaningful movement inside two to three months, and top-three positions in major cities in that window when the site already has some domain authority and a steady flow of reviews. A brand new domain typically needs five to seven weeks before it starts ranking at all, so build the site before you buy the second cart.",
  },
  {
    q: "What should the H1 on a catering website say?",
    a: "Answer three questions in one line: what you do, who you do it for, and where you do it. “Coffee Catering in Dallas, Texas for Corporate Events” works. Your company name does not, and neither does clever copy with no keyword in it. Fixing the H1 alone has moved sites from page three to page one.",
  },
  {
    q: "Do AI-written location pages work for catering SEO?",
    a: "Rarely, and they often do damage. Cloning one location page across twenty cities with the city name swapped produces duplicate content that Google either ignores or suppresses site-wide, and recovery can take six months or more. If a page is not internally linked and does not outrank your own home page for its target query, it is not earning its place.",
  },
  {
    q: "How many Google reviews does a caterer need?",
    a: "Fewer than most people assume, but they have to keep arriving. Cadence beats volume: 30 reviews with one added weekly will usually outperform 50 that stopped a year ago. The bigger risk is at the bottom end, since under five or ten reviews a single one-star does real damage to your booking rate.",
  },
];

/* ============================ SMALL PIECES ============================ */

function SectionH2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-16 font-heading font-thin not-italic text-[1.9em] leading-[1.15] tracking-[-0.01em] text-[#261f15] sm:text-[2.2em]">
      {children}
    </h2>
  );
}

function Paragraph({ children }: { children: React.ReactNode }) {
  return (
    <p className="mt-5 font-sans text-[1.05em] leading-[1.75] text-[#261f15]/80">{children}</p>
  );
}

function ArticleTable({
  head,
  children,
}: {
  head: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="le-podcast-table-scroll mt-8 overflow-x-auto rounded-2xl border border-[#c6a66a]/25">
      <table className="w-full min-w-[560px] border-collapse text-left">
        <thead className="bg-[#261f15] text-[#ededd5]">{head}</thead>
        <tbody>{children}</tbody>
      </table>
    </div>
  );
}

const th = "whitespace-nowrap px-3 py-2.5 font-sans text-[0.62em] font-semibold uppercase tracking-[0.16em] sm:px-5 sm:py-3";
const td = "border-t border-[#261f15]/8 px-3 py-3 font-sans text-[0.875em] leading-relaxed text-[#261f15]/80 sm:px-5 sm:py-4";

/* ============================ PAGE ==================================== */

export default function PodcastEpisodeOnePage() {
  return (
    <main className="relative w-full overflow-x-clip bg-[#ededd5] text-[#261f15] selection:bg-[#c9932b] selection:text-[#261f15]">
      <style>{`
        .le-podcast-table-scroll { scrollbar-width: thin; scrollbar-color: #c6a66a transparent; }
        .le-podcast-table-scroll::-webkit-scrollbar { height: 6px; }
        .le-podcast-table-scroll::-webkit-scrollbar-track { background: transparent; }
        .le-podcast-table-scroll::-webkit-scrollbar-thumb { background-color: #c6a66a; border-radius: 999px; }
      `}</style>

      <section className="relative w-full pb-24 pt-40 md:pb-32 md:pt-48">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 z-0 mx-auto flex w-full max-w-[1480px] justify-between px-6 md:px-12"
        >
          {[0, 1, 2, 3, 4].map((i) => (
            <span key={i} className="h-full w-px bg-[#261f15]/[0.07]" />
          ))}
        </div>

        <div className="relative z-20 mx-auto w-full max-w-[820px] px-6 md:px-12">
          {/* -------------------------- head -------------------------- */}
          <span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#c6a66a]/15 px-3 py-1 font-sans text-[0.58rem] font-semibold uppercase tracking-[0.2em] text-[#8a6f3d]">
            <span aria-hidden="true">✦</span>
            Podcast — Episode 1
          </span>

          <h1 className="mt-5 font-heading font-thin not-italic text-[clamp(2.2rem,4.8vw,3.4rem)] leading-[1.08] tracking-[-0.01em] text-[#261f15]">
            What Three Years of Catering SEO Actually Taught Us
          </h1>

          <p className="mt-5 font-sans text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-[#261f15]/45">
            Kent Sheridan, Zane &amp; Gvantsa
            <span className="mx-2 text-[#8a6f3d]/70">✦</span>
            August 25, 2026
            <span className="mx-2 text-[#8a6f3d]/70">✦</span>
            {RUNTIME}
          </p>

          <Paragraph>
            Over 95% of our clients&rsquo; leads come from Google. Under 10% come from
            Instagram, and that holds true even for the clients with tens of
            thousands of followers. That single split is the reason this podcast
            exists, and it is the thread running through the whole first episode.
          </Paragraph>
          <Paragraph>
            Kent, Zane, and Gvantsa sat down for an hour and twenty minutes to talk
            about what changed in catering SEO between 2023 and now: what used to
            work, what stopped working, what we got wrong, and the handful of
            things that still move rankings faster than anything else. Below is
            the full episode, the short version of every lesson in it, and an
            abbreviated transcript.
          </Paragraph>

          {/* -------------------------- video -------------------------- */}
          <VideoEmbed
            youtubeId={YOUTUBE_ID}
            title="What Three Years of Catering SEO Actually Taught Us | LocalEyes Podcast Ep. 1"
            runtime={RUNTIME}
          />

          {/* ---------------- Google vs Instagram stat ------------------ */}
          <div className="mt-10 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-[#261f15]/12 bg-[#261f15]/12">
            <div className="flex flex-col items-center gap-2 bg-[#261f15] px-4 py-8 text-center sm:py-10">
              <span className="font-heading font-thin not-italic text-[3rem] leading-none tracking-[-0.02em] text-[#c6a66a] sm:text-[3.6rem]">
                95%+
              </span>
              <span className="font-sans text-[0.68rem] font-semibold uppercase tracking-[0.14em] text-[#ededd5]/70">
                of client leads come from Google
              </span>
            </div>
            <div className="flex flex-col items-center gap-2 bg-[#f7f5e8] px-4 py-8 text-center sm:py-10">
              <span className="font-heading font-thin not-italic text-[3rem] leading-none tracking-[-0.02em] text-[#261f15]/40 sm:text-[3.6rem]">
                &lt;10%
              </span>
              <span className="font-sans text-[0.68rem] font-semibold uppercase tracking-[0.14em] text-[#261f15]/50">
                come from Instagram, even with large followings
              </span>
            </div>
          </div>

          {/* -------------------------- short version -------------------------- */}
          <SectionH2>The short version</SectionH2>
          <Paragraph>If you only read one part of this page, read this.</Paragraph>
          <ol className="mt-5 flex list-decimal flex-col gap-3 pl-5 marker:font-semibold marker:text-[#8a6f3d]">
            {SHORT_VERSION.map((line) => (
              <li key={line} className="pl-1 font-sans text-[1.05em] leading-[1.7] text-[#261f15]/80">
                {line}
              </li>
            ))}
          </ol>

          {/* -------------------------- why google -------------------------- */}
          <SectionH2>Why Google beats Instagram for catering leads</SectionH2>
          <Paragraph>
            This was the most contested point three years ago and it is close to
            settled now. Caterers used to arrive at a sales call genuinely torn
            between putting money into social and putting money into their site.
          </Paragraph>
          <Paragraph>
            The data ended that argument. Across our client base, over 95% of
            inbound leads come from Google, self-reported by the customer on the
            inquiry form and confirmed in analytics. Clients with strong
            Instagram followings still see under 10% of leads originate there. A
            following is not a pipeline.
          </Paragraph>
          <Paragraph>
            The structural reason is intent. Someone scrolling Instagram is not
            trying to book a coffee cart for a 200-person sales kickoff in eleven
            days. Someone typing &ldquo;coffee catering Chicago&rdquo; is. Around
            75% of Google traffic goes to the top three results, so the gap
            between position two and position seven is not incremental, it is
            most of the market.
          </Paragraph>
          <Paragraph>
            If your site is invisible and you cannot work out why, the three most
            common causes are covered in our breakdown of{" "}
            <a
              href="/blog/why-mobile-caterers-get-zero-leads-from-google"
              className="text-[#8a6f3d] underline decoration-[#8a6f3d]/30 underline-offset-4 transition-colors duration-300 hover:text-[#6b552f] hover:decoration-[#6b552f]"
            >
              why mobile caterers get zero leads from Google
            </a>
            .
          </Paragraph>

          {/* -------------------------- 2023 vs 2026 -------------------------- */}
          <SectionH2>What actually changed between 2023 and now</SectionH2>
          <ArticleTable
            head={
              <tr>
                <th className={th}></th>
                <th className={th}>2023</th>
                <th className={th}>2026</th>
              </tr>
            }
          >
            {ERA_COMPARISON.map((row) => (
              <tr key={row.label} className="odd:bg-[#f7f5e8]">
                <td className={`${td} font-semibold text-[#261f15]`}>{row.label}</td>
                <td className={td}>{row.y2023}</td>
                <td className={`${td} text-[#261f15]`}>{row.y2026}</td>
              </tr>
            ))}
          </ArticleTable>
          <Paragraph>
            The uncomfortable version of that table: the easy era is over. Speed
            to top three still happens, and we still see it in major markets, but
            it now requires the site, the reviews, and the content working
            together rather than any one of them carrying the rest.
          </Paragraph>

          {/* -------------------------- three W's -------------------------- */}
          <SectionH2>The three W&rsquo;s: how to write an H1 that ranks</SectionH2>
          <Paragraph>
            Gvantsa&rsquo;s answer to &ldquo;what is the first warning sign on a
            site that gets no leads&rdquo; was immediate: the H1. Either it is
            not marked up as an H1 at all, or it is marketing copy that says
            nothing Google can use.
          </Paragraph>
          <Paragraph>The formula is three questions, answered in one line:</Paragraph>

          <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
            {[
              { w: "What", q: "do you do?" },
              { w: "Who", q: "do you do it for?" },
              { w: "Where", q: "do you do it?" },
            ].map((item) => (
              <div
                key={item.w}
                className="rounded-2xl border border-[#261f15]/12 bg-[#f7f5e8] px-6 py-7 text-center"
              >
                <p className="font-heading font-thin not-italic text-3xl text-[#8a6f3d]">{item.w}</p>
                <p className="mt-1.5 font-sans text-sm text-[#261f15]/65">{item.q}</p>
              </div>
            ))}
          </div>

          <div className="mt-6 rounded-2xl border border-[#c6a66a]/35 bg-[#261f15] px-6 py-7 sm:px-8 sm:py-8">
            <p className="font-sans text-[0.62rem] font-semibold uppercase tracking-[0.2em] text-[#c6a66a]">
              Worked example — a mobile bar in New York
            </p>
            <p className="mt-3 font-heading font-thin not-italic text-xl leading-[1.35] text-[#ededd5] sm:text-2xl">
              &ldquo;Cocktail Bar Catering and Professional Bartenders in New York
              City for Corporate and Private Events.&rdquo;
            </p>
          </div>

          <Paragraph>
            It is not poetry. It fits above the fold, it carries the keyword, and
            a visitor understands the business in about two seconds.
          </Paragraph>
          <Paragraph>
            What it replaces is the thing almost every catering site starts
            with: a company name as the H1, or something like &ldquo;Lattes,
            Love and Laughs.&rdquo; Fixing the H1 alone has been enough to move a
            site from page three to page one, which makes it the highest
            return-per-minute change on this list.
          </Paragraph>

          <p className="mt-8 font-sans text-[0.68rem] font-semibold uppercase tracking-[0.16em] text-[#261f15]/50">
            The rest of the above-the-fold checklist
          </p>
          <div className="mt-4 grid grid-cols-1 gap-px overflow-hidden rounded-2xl border border-[#261f15]/12 bg-[#261f15]/12 sm:grid-cols-2">
            {ABOVE_FOLD_ITEMS.map((item) => (
              <div key={item.n} className="flex items-start gap-3 bg-[#f7f5e8] px-5 py-4">
                <span className="font-heading font-thin not-italic text-lg text-[#c6a66a]">{item.n}</span>
                <span className="mt-1 font-sans text-sm leading-relaxed text-[#261f15]/75">{item.text}</span>
              </div>
            ))}
          </div>

          <Paragraph>
            Above the fold is worth roughly five times any other section of the
            page, and around 80% of visitors leave within one to two full
            scrolls. Everything that matters goes near the top.
          </Paragraph>

          {/* -------------------------- SEO vs branding -------------------------- */}
          <SectionH2>Does SEO clash with branding?</SectionH2>
          <Paragraph>
            Almost everyone assumes it does. It does not, and the reason is
            mechanical rather than philosophical.
          </Paragraph>
          <Paragraph>
            Take the extreme case. You build a page optimized purely for a
            crawler, with no design and nothing that convinces a human you can
            actually run their event. It might rank briefly. Then visitors land,
            bounce straight back to the search results, and Google reads that
            behavior as a signal that the page did not answer the query. The
            ranking goes with it.
          </Paragraph>
          <Paragraph>
            So a badly designed site eventually damages the SEO that got it
            ranked. The order of operations matters more than the tradeoff: get
            people to the site first, then obsess over the last three pixels. If
            nobody is landing, the design is not making you money either way.
          </Paragraph>

          {/* -------------------------- review engine -------------------------- */}
          <SectionH2>The review engine</SectionH2>
          <Paragraph>
            Zane&rsquo;s answer to &ldquo;what separates the businesses that grow
            from the ones nobody finds&rdquo; was fresh content and consistent
            reviews, in that order of how often it gets ignored.
          </Paragraph>
          <Paragraph>
            The part most operators miss is that cadence beats volume. A profile
            sitting at 30 reviews that adds one every week will typically pass a
            profile stuck at 50 that stopped a year ago, and it will often pass
            it before it reaches 50 itself. Google is reading the pattern, not
            just the count.
          </Paragraph>
          <Paragraph>
            The practical move is to build review collection into the event
            instead of chasing it afterward:
          </Paragraph>
          <ArticleTable
            head={
              <tr>
                <th className={th}>Tactic</th>
                <th className={th}>Where it happens</th>
                <th className={th}>Why it works</th>
              </tr>
            }
          >
            {REVIEW_TACTICS.map((row) => (
              <tr key={row.tactic} className="odd:bg-[#f7f5e8]">
                <td className={`${td} font-semibold text-[#261f15]`}>{row.tactic}</td>
                <td className={td}>{row.where}</td>
                <td className={td}>{row.why}</td>
              </tr>
            ))}
          </ArticleTable>
          <Paragraph>
            Under five or ten reviews, a single one-star does real damage. That is
            the other reason to start the engine early rather than after the
            first bad night. More on how reviews and rankings interact in{" "}
            <a
              href="/blog/why-google-reviews-outrank-your-website"
              className="text-[#8a6f3d] underline decoration-[#8a6f3d]/30 underline-offset-4 transition-colors duration-300 hover:text-[#6b552f] hover:decoration-[#6b552f]"
            >
              why Google reviews outrank your website
            </a>
            .
          </Paragraph>

          {/* -------------------------- DIY AI SEO -------------------------- */}
          <SectionH2>Why DIY AI SEO is not ranking</SectionH2>
          <Paragraph>
            This came up as its own segment and it is the most current problem on
            the list. An operator asks ChatGPT or Claude how to optimize their
            site, does everything it says, checks every box, and does not move.
          </Paragraph>
          <Paragraph>Two reasons, both structural.</Paragraph>
          <Paragraph>
            The first is bad keyword input. AI models pull their sense of a
            market largely from what is already ranking. If the caterers in your
            city all have the wrong keywords in the wrong places, that is the
            pattern the model learns and hands back to you. It will confidently
            tell you to put the wrong term in your H1 because the wrong term is
            what it saw.
          </Paragraph>
          <Paragraph>
            The second is duplication at scale. The most common DIY move is
            generating one location page and cloning it across twenty cities
            with the city name swapped. Google indexes some, ignores most, and
            in the worst cases effectively suppresses the whole domain for
            duplicate content. It does not send a notice. Recovery runs six
            months or longer.
          </Paragraph>
          <Paragraph>
            Two tests for any location or service page you have already
            published:
          </Paragraph>
          <ol className="mt-5 flex list-decimal flex-col gap-2 pl-5 marker:font-semibold marker:text-[#8a6f3d]">
            <li className="pl-1 font-sans text-[1.05em] leading-[1.7] text-[#261f15]/80">
              Is it linked from somewhere else on your site? An orphan page is a
              page Google has no reason to trust.
            </li>
            <li className="pl-1 font-sans text-[1.05em] leading-[1.7] text-[#261f15]/80">
              Does it outrank your own home page for the query it was built for?
              If your home page still comes up first for &ldquo;coffee catering
              Austin,&rdquo; the Austin page did nothing and is costing you crawl
              budget.
            </li>
          </ol>
          <Paragraph>
            If a page fails both, delete it. The full structural approach lives
            in our{" "}
            <a
              href="/blog/local-seo-for-mobile-caterers"
              className="text-[#8a6f3d] underline decoration-[#8a6f3d]/30 underline-offset-4 transition-colors duration-300 hover:text-[#6b552f] hover:decoration-[#6b552f]"
            >
              complete local SEO guide for mobile caterers
            </a>
            .
          </Paragraph>

          {/* -------------------------- results -------------------------- */}
          <SectionH2>What we got right, and what we would tell a caterer starting tomorrow</SectionH2>
          <Paragraph>
            The results we can point to: a client who went from 4 leads to 34 in
            two months, top-three positions in NYC, Philadelphia, Orlando,
            Chicago and Los Angeles, and a Los Angeles coffee caterer who hit
            number one for their money keyword inside two months and held it
            while the market got significantly harder around them.
          </Paragraph>
          <Paragraph>
            The result Kent likes most is different. A New York operator who was
            already ranking, already making good money, already near the top of
            page one for three keywords. The work was not fixing anything
            broken. It was finding the ten keywords she was not ranking for at
            all. Her revenue roughly doubled. Being number one for the two
            keywords you happen to check is not the same as owning your market.
          </Paragraph>
          <Paragraph>
            And the closing advice, unedited in spirit: get the website. Do not
            run your business on Instagram alone. Build every channel that can
            bring you a lead, then grow them one at a time.
          </Paragraph>

          {/* -------------------------- chapters -------------------------- */}
          <SectionH2>Episode chapters</SectionH2>
          <ArticleTable
            head={
              <tr>
                <th className={th}>Time</th>
                <th className={th}>Topic</th>
              </tr>
            }
          >
            {CHAPTERS.map((row) => (
              <tr key={row.t} className="odd:bg-[#f7f5e8]">
                <td className={`${td} whitespace-nowrap font-semibold tabular-nums text-[#8a6f3d]`}>{row.t}</td>
                <td className={td}>{row.topic}</td>
              </tr>
            ))}
          </ArticleTable>

          {/* -------------------------- transcript -------------------------- */}
          <SectionH2>Abbreviated transcript</SectionH2>
          <Paragraph>Lightly edited for readability. Timestamps are approximate.</Paragraph>

          {TRANSCRIPT.map((section) => (
            <div key={section.heading}>
              <h3 className="mt-10 font-heading font-thin not-italic text-[1.35em] leading-[1.25] tracking-[-0.005em] text-[#261f15]">
                {section.heading}{" "}
                <span className="font-sans text-[0.6em] font-semibold uppercase tracking-[0.14em] text-[#8a6f3d]">
                  ({section.time})
                </span>
              </h3>
              {section.turns.map((turn, ti) => (
                <div key={ti}>
                  {turn.lines.map((line, li) => (
                    <p
                      key={li}
                      className="mt-5 font-sans text-[1.05em] leading-[1.75] text-[#261f15]/80"
                    >
                      {li === 0 && (
                        <span className="font-semibold text-[#8a6f3d]">{turn.speaker}: </span>
                      )}
                      {line}
                    </p>
                  ))}
                </div>
              ))}
            </div>
          ))}

          <h3 className="mt-10 font-heading font-thin not-italic text-[1.35em] leading-[1.25] tracking-[-0.005em] text-[#261f15]">
            Rapid fire{" "}
            <span className="font-sans text-[0.6em] font-semibold uppercase tracking-[0.14em] text-[#8a6f3d]">
              (1:13:48)
            </span>
          </h3>
          <div className="mt-5 flex flex-col divide-y divide-[#261f15]/10 rounded-2xl border border-[#261f15]/10">
            {RAPID_FIRE.map((row) => (
              <div key={row.q} className="flex flex-col gap-1.5 px-5 py-4 sm:flex-row sm:gap-6 sm:px-6">
                <p className="shrink-0 font-sans text-sm font-semibold text-[#261f15] sm:w-[46%]">
                  {row.q}
                </p>
                <p className="font-sans text-sm leading-relaxed text-[#261f15]/70">{row.a}</p>
              </div>
            ))}
          </div>

          {/* -------------------------- FAQ -------------------------- */}
          <SectionH2>FAQ</SectionH2>
          <EpisodeFaq items={FAQ_ITEMS} />

          {/* -------------------------- closing CTA -------------------------- */}
          <div className="mt-16 rounded-[1.75rem] border border-[#c6a66a]/35 bg-[#261f15] px-8 py-12 text-center text-[#ededd5] md:px-14 md:py-16">
            <h2 className="font-heading font-thin not-italic text-[clamp(1.7rem,3vw,2.3rem)] leading-[1.15] tracking-[-0.01em]">
              Where to start
            </h2>
            <p className="mx-auto mt-4 max-w-md font-sans text-sm leading-relaxed text-[#ededd5]/65">
              If you want the same read on your own business that we give
              clients, take the free Growth Assessment. It takes about ten
              minutes, covers pricing, reviews, staffing and site structure, not
              just SEO, and it tells you which gap is actually costing you money
              right now.
            </p>
            <div className="mt-8 flex justify-center">
              <GrowthDiagnosticCta label="Run My Free Growth Assessment" />
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
